spring:
  application:
    name: 'Cyno-Desu'
  datasource:
    url: jdbc:postgresql://localhost:5454/dev
    driverClassName: org.postgresql.Driver
    username: cyno
    password: desu
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 8081
logging:
    level:
#      org.springframework.security: DEBUG
#      thymeleaf: DEBUG
      org.hibernate: DEBUG
